### PR TITLE
Add migration for new `remember_token` field.

### PR DESCRIPTION
**Pull request by bcho**
Also revoked useless field from 22c7aaf9fb4915.

### CODE REVIEW

**Comment by bcho** [comment]
@Yannyezixin please review this.

**Comment by Yannyezixin** [comment]
@bcho  I' get it

**Comment by bcho** [comment]
@Yannyezixin 代码有问题么？

**Comment by Yannyezixin** [comment]
@bcho 应该没有，可以参考https://gist.github.com/denvers/10828426

**Pull request merged**
